# Generated by Django 2.2.10 on 2020-08-18 17:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('market', '0003_auto_20200730_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productsinorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productsinorder',
            name='product',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductsInOrder',
        ),
    ]
